# Generated by Django 6.0.2 on 2026-02-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nihalhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
