# Generated by Django 6.0.2 on 2026-02-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nihalhome', '0002_item_sold_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold_at',
        ),
    ]
